api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/vendor/metaclass-nl/filter-bundle/tests/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
