api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/vendor/metaclass-nl/filter-bundle/tests/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    graphql:
        enabled: false
        default_ide: false
        graphiql:
            enabled: false
        graphql_playground:
            enabled: false
    formats:
        jsonld: [ 'application/ld+json' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
#    event_listeners_backward_compatibility_layer: false - does not work with 4.0.0
#    keep_legacy_inflector: false - does not work with 4.0.0
    use_symfony_listeners: false
    serializer:
        hydra_prefix: false
